- hosts: all
  become: true
  roles:
    - common

- hosts: model
  become: true
  roles:
    - postgres

- hosts: api
  become: true
  roles:
    - api

- hosts: viewer
  become: true
  roles:
    - frontend
